# Use Node.js image as base
FROM node:18

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port
EXPOSE 5001

# Start the application
CMD ["node", "server.js"]
